name: 'gh-action-setup-nextflow'
description: 'A GitHub Action to setup Nextflow.'
inputs:
  version:
    description: 'Version'
    required: false
    default: '21.10'

runs:
  using: 'composite'
  steps:
    - name: 'Check for a cached Nextflow version'
      uses: actions/cache@v2
      id: nextflow-cache
      with:
        path: |
          /usr/local/bin/nextflow
          ~/.nextflow
        key: ${{ runner.os }}-nextflow-${{ inputs.version }}

    - name: 'Download Nextflow'
      if: steps.nextflow-cache.outputs.any_changed != 'true'
      shell: bash
      run: |  
        wget -qO- https://github.com/nextflow-io/nextflow/releases/download/v${{ inputs.version }}/nextflow-${{ inputs.version}}-all | bash \
        && chmod +x nextflow \
        && sudo mv nextflow /usr/local/bin/

