name: 'gh-action-setup-nextflow'
description: 'A GitHub Action to setup Nextflow.'
inputs:
  version:
    description: 'Version'
    required: false
    default: '21.10.0'

runs:
  using: 'composite'
  steps:
    - name: 'Check for a cached Nextflow version'
      uses: actions/cache@v2
      id: nextflow-cache
      with:
        path: |
          /usr/local/bin/nextflow
          ~/.nextflow
        key: ${{ runner.os }}-nextflow-${{ inputs.version }}

    - name: 'Install Nextflow'
      if: steps.nextflow-cache.outputs.any_changed != 'true'
      shell: bash
      run: |
        wget -qO- https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/


